# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Alex/Dropbox/Calexo/0Projets/SideScreen/SideScreen_RpiApp/rpiscreen.ui'
#
# Created: Wed Oct  1 15:12:01 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RpiScreen(object):
    def setupUi(self, RpiScreen):
        RpiScreen.setObjectName(_fromUtf8("RpiScreen"))
        RpiScreen.resize(750, 1032)
        self.centralWidget = QtGui.QWidget(RpiScreen)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.hlLevels = QtGui.QHBoxLayout()
        self.hlLevels.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.hlLevels.setMargin(10)
        self.hlLevels.setObjectName(_fromUtf8("hlLevels"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbProc1 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc1.setProperty("value", 100)
        self.pbProc1.setOrientation(QtCore.Qt.Vertical)
        self.pbProc1.setObjectName(_fromUtf8("pbProc1"))
        self.horizontalLayout.addWidget(self.pbProc1)
        self.pbProc2 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc2.setProperty("value", 100)
        self.pbProc2.setOrientation(QtCore.Qt.Vertical)
        self.pbProc2.setObjectName(_fromUtf8("pbProc2"))
        self.horizontalLayout.addWidget(self.pbProc2)
        self.pbProc3 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc3.setProperty("value", 100)
        self.pbProc3.setOrientation(QtCore.Qt.Vertical)
        self.pbProc3.setObjectName(_fromUtf8("pbProc3"))
        self.horizontalLayout.addWidget(self.pbProc3)
        self.pbProc4 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc4.setProperty("value", 100)
        self.pbProc4.setOrientation(QtCore.Qt.Vertical)
        self.pbProc4.setObjectName(_fromUtf8("pbProc4"))
        self.horizontalLayout.addWidget(self.pbProc4)
        self.pbProc5 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc5.setProperty("value", 100)
        self.pbProc5.setOrientation(QtCore.Qt.Vertical)
        self.pbProc5.setObjectName(_fromUtf8("pbProc5"))
        self.horizontalLayout.addWidget(self.pbProc5)
        self.pbProc6 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc6.setProperty("value", 100)
        self.pbProc6.setOrientation(QtCore.Qt.Vertical)
        self.pbProc6.setObjectName(_fromUtf8("pbProc6"))
        self.horizontalLayout.addWidget(self.pbProc6)
        self.pbProc7 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc7.setProperty("value", 100)
        self.pbProc7.setOrientation(QtCore.Qt.Vertical)
        self.pbProc7.setObjectName(_fromUtf8("pbProc7"))
        self.horizontalLayout.addWidget(self.pbProc7)
        self.pbProc8 = QtGui.QProgressBar(self.centralWidget)
        self.pbProc8.setProperty("value", 100)
        self.pbProc8.setOrientation(QtCore.Qt.Vertical)
        self.pbProc8.setObjectName(_fromUtf8("pbProc8"))
        self.horizontalLayout.addWidget(self.pbProc8)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.lcdMoyProc = QtGui.QLCDNumber(self.centralWidget)
        self.lcdMoyProc.setSmallDecimalPoint(False)
        self.lcdMoyProc.setDigitCount(3)
        self.lcdMoyProc.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdMoyProc.setProperty("intValue", 100)
        self.lcdMoyProc.setObjectName(_fromUtf8("lcdMoyProc"))
        self.verticalLayout_4.addWidget(self.lcdMoyProc)
        self.hlLevels.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlLevels.addItem(spacerItem)
        self.pbMem = QtGui.QProgressBar(self.centralWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pbMem.setPalette(palette)
        self.pbMem.setProperty("value", 100)
        self.pbMem.setTextVisible(False)
        self.pbMem.setOrientation(QtCore.Qt.Vertical)
        self.pbMem.setInvertedAppearance(False)
        self.pbMem.setObjectName(_fromUtf8("pbMem"))
        self.hlLevels.addWidget(self.pbMem)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.dialVolume = QtGui.QDial(self.centralWidget)
        self.dialVolume.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.dialVolume.setObjectName(_fromUtf8("dialVolume"))
        self.verticalLayout_5.addWidget(self.dialVolume)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.lcdFreeMem = QtGui.QLCDNumber(self.centralWidget)
        self.lcdFreeMem.setObjectName(_fromUtf8("lcdFreeMem"))
        self.verticalLayout_5.addWidget(self.lcdFreeMem)
        self.hlLevels.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.hlLevels)
        self.lblInfo = QtGui.QLabel(self.centralWidget)
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.verticalLayout_3.addWidget(self.lblInfo)
        self.hlPics1 = QtGui.QHBoxLayout()
        self.hlPics1.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.hlPics1.setContentsMargins(10, -1, -1, -1)
        self.hlPics1.setObjectName(_fromUtf8("hlPics1"))
        self.pic7 = QtGui.QLabel(self.centralWidget)
        self.pic7.setMinimumSize(QtCore.QSize(233, 250))
        self.pic7.setAlignment(QtCore.Qt.AlignCenter)
        self.pic7.setObjectName(_fromUtf8("pic7"))
        self.hlPics1.addWidget(self.pic7)
        self.pic8 = QtGui.QLabel(self.centralWidget)
        self.pic8.setMinimumSize(QtCore.QSize(233, 250))
        self.pic8.setAlignment(QtCore.Qt.AlignCenter)
        self.pic8.setObjectName(_fromUtf8("pic8"))
        self.hlPics1.addWidget(self.pic8)
        self.pic9 = QtGui.QLabel(self.centralWidget)
        self.pic9.setMinimumSize(QtCore.QSize(233, 250))
        self.pic9.setAlignment(QtCore.Qt.AlignCenter)
        self.pic9.setObjectName(_fromUtf8("pic9"))
        self.hlPics1.addWidget(self.pic9)
        self.verticalLayout_3.addLayout(self.hlPics1)
        self.hlPics2 = QtGui.QHBoxLayout()
        self.hlPics2.setObjectName(_fromUtf8("hlPics2"))
        self.pic4 = QtGui.QLabel(self.centralWidget)
        self.pic4.setMinimumSize(QtCore.QSize(0, 250))
        self.pic4.setAlignment(QtCore.Qt.AlignCenter)
        self.pic4.setObjectName(_fromUtf8("pic4"))
        self.hlPics2.addWidget(self.pic4)
        self.pic5 = QtGui.QLabel(self.centralWidget)
        self.pic5.setMinimumSize(QtCore.QSize(0, 250))
        self.pic5.setAlignment(QtCore.Qt.AlignCenter)
        self.pic5.setObjectName(_fromUtf8("pic5"))
        self.hlPics2.addWidget(self.pic5)
        self.pic6 = QtGui.QLabel(self.centralWidget)
        self.pic6.setMinimumSize(QtCore.QSize(0, 250))
        self.pic6.setAlignment(QtCore.Qt.AlignCenter)
        self.pic6.setObjectName(_fromUtf8("pic6"))
        self.hlPics2.addWidget(self.pic6)
        self.verticalLayout_3.addLayout(self.hlPics2)
        self.hlPics3 = QtGui.QHBoxLayout()
        self.hlPics3.setObjectName(_fromUtf8("hlPics3"))
        self.pic1 = QtGui.QLabel(self.centralWidget)
        self.pic1.setMinimumSize(QtCore.QSize(0, 250))
        self.pic1.setAlignment(QtCore.Qt.AlignCenter)
        self.pic1.setObjectName(_fromUtf8("pic1"))
        self.hlPics3.addWidget(self.pic1)
        self.pic2 = QtGui.QLabel(self.centralWidget)
        self.pic2.setMinimumSize(QtCore.QSize(0, 250))
        self.pic2.setAlignment(QtCore.Qt.AlignCenter)
        self.pic2.setObjectName(_fromUtf8("pic2"))
        self.hlPics3.addWidget(self.pic2)
        self.pic3 = QtGui.QLabel(self.centralWidget)
        self.pic3.setMinimumSize(QtCore.QSize(0, 250))
        self.pic3.setAlignment(QtCore.Qt.AlignCenter)
        self.pic3.setObjectName(_fromUtf8("pic3"))
        self.hlPics3.addWidget(self.pic3)
        self.verticalLayout_3.addLayout(self.hlPics3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        RpiScreen.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(RpiScreen)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuSide_Screen = QtGui.QMenu(self.menuBar)
        self.menuSide_Screen.setObjectName(_fromUtf8("menuSide_Screen"))
        RpiScreen.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(RpiScreen)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        RpiScreen.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(RpiScreen)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        RpiScreen.setStatusBar(self.statusBar)
        self.action_Exit = QtGui.QAction(RpiScreen)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.menuSide_Screen.addAction(self.action_Exit)
        self.menuBar.addAction(self.menuSide_Screen.menuAction())

        self.retranslateUi(RpiScreen)
        QtCore.QMetaObject.connectSlotsByName(RpiScreen)

    def retranslateUi(self, RpiScreen):
        RpiScreen.setWindowTitle(_translate("RpiScreen", "RpiScreen", None))
        self.pbProc1.setToolTip(_translate("RpiScreen", "<html><head/><body><p>Proc 1</p></body></html>", None))
        self.pbMem.setToolTip(_translate("RpiScreen", "<html><head/><body><p>Free Memory (RAM)</p></body></html>", None))
        self.lblInfo.setText(_translate("RpiScreen", "Loading...", None))
        self.pic7.setText(_translate("RpiScreen", "7", None))
        self.pic8.setText(_translate("RpiScreen", "8", None))
        self.pic9.setText(_translate("RpiScreen", "9", None))
        self.pic4.setText(_translate("RpiScreen", "4", None))
        self.pic5.setText(_translate("RpiScreen", "5", None))
        self.pic6.setText(_translate("RpiScreen", "6", None))
        self.pic1.setText(_translate("RpiScreen", "1", None))
        self.pic2.setText(_translate("RpiScreen", "2", None))
        self.pic3.setText(_translate("RpiScreen", "3", None))
        self.menuSide_Screen.setTitle(_translate("RpiScreen", "Side Screen", None))
        self.action_Exit.setText(_translate("RpiScreen", "&Exit", None))

